package buct.tzx.buildtools.utils;

import java.io.File;
import java.util.ArrayList;

// scan工具类，所有被扫到的类都会被add进去
public class ScanConsts {
    public static final String PLUGIN_NAME = "buct.tzx.routergenerated";
    /**
     * The register code is generated into this class
     */
    public static final String GENERATE_TO_CLASS_NAME = "buct/tzx/routerapi/RouterManager";
    /**
     * you know. this is the class file(or entry in jar file) name
     */
    public static final String GENERATE_TO_CLASS_FILE_NAME = GENERATE_TO_CLASS_NAME + ".class";
    /**
     * The register code is generated into this method
     */
    public static final String GENERATE_TO_METHOD_NAME = "autoInjectIntoMap";
    /**
     * The package name of the class generated by the annotationProcessor
     */
    public static final String ROUTER_CLASS_PACKAGE_NAME = "buct/tzx/routergenerated";
    /**
     * The package name of the interfaces
     */
    private static final String INTERFACE_PACKAGE_NAME = "buct/tzx/routerannotation/";

    /**
     * register method name in class: {@link #GENERATE_TO_CLASS_NAME}
     */
    public static final String REGISTER_METHOD_NAME = "register";
    /**
     * scan for classes which implements this interface
     */
    public String interfaceName = "";

    /**
     * jar file which contains class: {@link #GENERATE_TO_CLASS_NAME}
     */
    public File fileContainsInitClass;
    /**
     * scan result for {@link #interfaceName}
     * class names in this list
     */
    public ArrayList<String> classList = new ArrayList<>();

    /**
     * constructor for arouter-auto-register settings
     * @param interfaceName interface to scan
     */
    public ScanConsts(String interfaceName){
        this.interfaceName = INTERFACE_PACKAGE_NAME + interfaceName;
    }

}
